# Generated by Django 4.1.3 on 2022-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
                ('app_name', models.CharField(max_length=50, verbose_name='App name')),
            ],
        ),
    ]
